/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sorting;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {
        int[] sampleArr = {8, 4, 23, 42, 16, 15};
        System.out.println(Arrays.toString(insertionSort(sampleArr)));
    }


    public static int[] insertionSort(int[] arr) {
        for (int i = 1; i < arr.length; i++) {
            int j = i - 1;
            int temp = arr[i];
            while (j >= 0 && temp < arr[j]) {
                arr[j + 1] = arr[j];
                j = j - 1;
            }
            arr[j + 1] = temp;
        }
        return arr;
    }
}
