/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class Library {
   public static void main(String[] args){

      HashTable<String,Integer> hashTable=new HashTable<>();
      hashTable.add("first",5);
      hashTable.add("second",100);
      System.out.println(hashTable.size());
      System.out.println(hashTable.numBuckets);
      System.out.println(hashTable.contains("first"));
      System.out.println(hashTable.contains("hi"));
      System.out.println(hashTable.get("second"));
   }


}
