/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Stack<Integer> stack=new Stack<>();
        stack.push(5);
        stack.push(2);
        stack.push(7);
        System.out.println(stack);
        System.out.println("removed value: "+stack.pop());
        System.out.println("top: "+stack.peek());
        System.out.println("stack is Empty: "+stack.isEmpty());
        Queue<Integer> queue=new Queue<>();
        queue.enqueue(5);
        queue.enqueue(2);
        queue.enqueue(7);
        System.out.println(queue);
        System.out.println("removed value: "+queue.dequeue());
        System.out.println("front: "+queue.peek());
        System.out.println("queue is Empty: "+queue.isEmpty());

        PseudoQueue<Integer> pseudoQueue=new PseudoQueue<>();
        pseudoQueue.enqueue(20);
        pseudoQueue.enqueue(15);
        pseudoQueue.enqueue(10);
        pseudoQueue.enqueue(5);
        System.out.println(pseudoQueue.toString());
        System.out.println(pseudoQueue.dequeue());
        System.out.println(pseudoQueue.toString());
    }

}
