/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

    //this is the main function.
    public static void main(String[] args) {
        LinkedList<Integer> mainList = new LinkedList<>();
        System.out.println(mainList.head);
        mainList.insert(5);
        System.out.println(mainList);
        mainList.insert(3);
        mainList.insert(10);
        mainList.insert(-1);
        mainList.append(2);
       mainList.insertBefore(-1,9);
        mainList.insertAfter(2,6);
        System.out.println(mainList);
        printLinkedListValues(mainList);
        System.out.println(mainList.includes(-1));
        System.out.println(mainList.includes(1));
        System.out.println(mainList.head.value);
    }

    //this is a method to print the values of linked list each one on a line.
    public static void printLinkedListValues(LinkedList mainList){
        Node current=mainList.head;
        while (current != null) {
            System.out.println(current.value);
            current = current.next;
        }

    }
}
